### ISSUE TITLE
pyEpiabm - read in parameters from .json file

### ISSUE THREAD

**Issue by KCGallagher** [SABS-R3-Epidemiology/epiabm#105]
Currently all stored in `pyEpiabm.core.parameters.py`

**Comment by Saketkr21** [comment]
Hii,
I have fixed this issue. But facing issues with creating PR. 
[My Repo](https://github.com/Saketkr21/epiabm.git )
New Code is in **development** branch.

Can anyone please help me with how to create PR for someone else Repo?
Thank you.

*Trying to make My First Open Source Contribution.*

**Comment by KCGallagher** [comment]
Hi @Saketkr21, very excited you want to be involved! The best way to contribute is to fork our repo and make changed on the fork, then you can create a PR from there - more instructions are available on this [contributing](https://gist.github.com/MarcDiethelm/7303312) page.

Apologies we don't yet have our own contributors guidelines set up yet - I will do this asap but it will match the general guidance on the link above

**Comment by KCGallagher** [comment]
Closed in #116
