### ISSUE TITLE
Functional tests for interventions

### ISSUE THREAD

**Issue by HenrietteCapel** [SABS-R3-Epidemiology/epiabm#186]
**Is your feature request related to a problem? Please describe.**
We only have unit tests for interventions, functional tests are missing.

**Describe the solution you'd like**
tests basic cases - for example that an intervention with 0 effectiveness doesn't change the overall simulation outcome at all, whereas completely effective interventions prevent transmission completely (for example quarantining should prevent infections outside of households

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or implementations you've considered.

**Comparison to CovidSim**
Give any relevant comparison to the CovidSim code, and describe any deviations from their functionality

**Additional context**

**Comment by jiayuanz3** [comment]
2. Household Quarantine: have to test with case isolation as the start of household quarantine is triggered by one individual's isolation start time: (a) set isolation_effectiveness = 1, isolation_house_effectiveness = 1, quarantine_house_effectiveness = 1, quarantine_spatial_effectiveness = 1, quarantine_place_effectiveness = [1, 1, 1, 1, 1, 1], number of each status should be same as those without InterventionSweep. (b) run with the quarantine_house_compliant = 1, quarantine_individual_compliant = 1 versus quarantine_house_compliant = 0.5, quarantine_individual_compliant = 0.5, the previous one should have more susceptible and less infectious people (can't check when compliant is 0, if the result is same as without intervention, because self isolation is involved).

**Comment by jiayuanz3** [comment]
3. Place Closure: ensure population are assigned to different types of places: set case_microcell_threshold = population's size + 1 (which means this intervention won't be triggered), then number of each status should be same as those without InterventionSweep. (b) set closure_household_infectiousness = 1, closure_spatial_params = 1,  then number of each status should be same as those without InterventionSweep. (c) set closure_household_infectiousness = 0.5, closure_spatial_params = 0.5, number of susceptible should be larger and total number of infectious should be smaller than without InterventionSweep. (d) closure_place_type = [1] versus closure_place_type = [1,2,3,4] (here more types of places will be closed), so the first simulation will have less susceptible and more infectious will than the second.

**Comment by jiayuanz3** [comment]
4. Social Distancing: 
(a) set case_microcell_threshold = population's size + 1 (which means this intervention won't be triggered), then number of each status should be same as those without InterventionSweep.
(b) set distancing_enhanced_prob all to 1 and distancing enhanced parameters (household, place, spatial) all to 1, the result should be same as without  InterventionSweep. 
(c) set half of the distancing_enhanced_prob to 0.5, and half to 1 versus all set to 1 (i.e. in the first case, some people will have non-enhanced social distancing, in the second case, all have enhanced social distancing), then the second case is expected to have more susceptible and less infectious.

**Comment by KCGallagher** [comment]
These are very comprehensive - you may not need to do all of these (although you're welcome to give it a go!) In each case the last options where you compare relative outcomes may not be necessary (and you'll think how you'd control for stochasticity - absolute results such as zero transmission outside of a household are definitely easier to test

**Comment by jiayuanz3** [comment]
In all functional tests, I compared the number of susceptible individuals of all age groups between two population. 

1. Case isolation:
(a) More people are susceptible when case isolation is present versus no intervention sweep.
(b) Less people are susceptible when threshold of infectious individuals to start case isolation increases.
(c) Less people are susceptible when the number of delay days increases.
(d) Less people are susceptible when the number of duration days decreases.
(e) More people are susceptible when the isolation probability increases.
(f) Less people are susceptible when the isolation effectiveness increases.

2. Place closure:
(a) More people are susceptible when place closure is present.
(b) Given the empty list of place to close, the result is the same as no intervention.
(c) More people are susceptible when more types of places are closed.
(d) Less people are susceptible when the closure spatial scaling factor increases.
(e) When the case threshold at microcell level exceeds the population, the result is the same as no intervention.
(f) Less people are susceptible when the case threshold at microcell level increases.

3. Social distancing:
(a) More people are susceptible when social distancing is present. 
(b) Less people are susceptible when the spatial enhanced susceptibility increases.
(c) Less people are susceptible when the enhanced social distancing probability decreases. 

4. Household quarantine:
(a) More people are susceptible when household quarantine is present.
