### ISSUE TITLE
Bypassing Recovered compartment feature

### ISSUE THREAD

**Issue by mghosh00** [SABS-R3-Epidemiology/epiabm#251]
**Is your feature request related to a problem? Please describe.**
We would like to begin implementing waning immunity for Epiabm. Currently once someone has Recovered, they remain there, and we would like to change this.

**Describe the solution you'd like**
Initially, we will update the simulation so that once someone has Recovered, they immediately return to the Susceptible compartment. This will be done via the transition matrices and will only occur if the user passes a flag to the simulation. Further issues will cover implementation of waning immunity.

**Comparison to CovidSim**
Not currently implemented in CovidSim.

**Additional context**
This is the first step towards having waning immunity implemented in Epiabm.

**Comment by tomcodewizard** [comment]
### Files to change:

**person.py/ init():**

add time_of_recovery or time_recovered attribute set to None

**simple_parameters.json , etc. (every simulation file):**

add use_waning_immunity = 0 or 1

add mean_recov_to_susc = large number

**simulation.py / congifure() , docstring:**

include waning immunity functionality

**Comment by tomcodewizard** [comment]
**Test Files**

- [ ] Tom : person, inverseCDF, simulation

- [ ] Matthew : host_progression_sweep,  transition_matrices

**Comment by tomcodewizard** [comment]
Need to now look at literature to try find how to change the transition probabilities, esp for the compartments ICU and ICU_recovery
