### ISSUE TITLE
InverseCDF returning potentially wrong values

### ISSUE THREAD

**Issue by mghosh00** [SABS-R3-Epidemiology/epiabm#255]
**Describe the bug**
In line 56 of inverse_cdf.py (icdf_choose_no_exp), we have discovered that some people (potentially erroneously) return a value of 0. This implies that their transition time between statuses is equal to 0 and so the person will transition between multiple statuses in the same time step.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add an if statement to check for value == 0 under line 56 of inverse_cdf.py
2. Add a break point on this new line
3. Run any functional test (e.g. test_distancing_functional.py) with the debugger
4. Step through the code, and you will see that a person goes from Susceptible -> Exposed -> InfectGP in one time step using the while loop of line 313 in host_progression_sweep.py

**Expected behaviour**
No person should step through multiple statuses in the same time step

**Desktop (please complete the following information):**
 - OS: Windows
 - Python/ C++ Version: 3.12

**Comment by mghosh00** [comment]
Not sure if this is an issue or not, as in the wiki it states that icdf can return the value of 0. This does mean that some people transition from Susceptible -> Exposed -> Infect_{*} in one time step. This can be changed if necessary.

**Comment by KCGallagher** [comment]
This currently replicates behaviour from CovidSim - while I appreciate the concern I think that the is insufficent evidence to disprove the assertion that this transition may occur (with some small probability). While this is worth bearing in mind for future reporting methods, I will resolve this issue on that basis
