### ISSUE TITLE
Simulation of Ireland

### ISSUE THREAD

**Issue by mghosh00** [SABS-R3-Epidemiology/epiabm#264]
**Is your feature request related to a problem? Please describe.**
We wish to simulate the population of Ireland, as there is good spatial heterogeneity and the country has a reasonable population size (~5 million).

**Describe the solution you'd like**
* Retrieve geographical parameters from EpiGeoPop
* Modify any other parameters necessary (e.g. household parameters)

**Additional context**
This data will be used across EpiOS stratified sampling, branching processes and SEIR inference

**Comment by mghosh00** [comment]
## Parameters

Here are a list of parameters from the .json files:

### Hyperparameters

- [ ] basic_reproduction_num
- [ ] mcell_num_per_cell
- [ ] ave_places_per_mcell
- [ ] infection_radius
- [ ] time_steps_per_day

### Disease parameters

- [ ] latent_period
- [ ] asympt_infect_period
- [ ] mean_x_to_y (10 params)
- [ ] x_icdf (12 lists)
- [ ] CDF_RES
- [ ] prob_symptomatic
- [ ] sympt_infectiousness
- [ ] asympt_infectiousness
- [ ] infectiousness_prof
- [ ] latent_to_sympt_delay
- [ ] max_infectious_steps
- [ ] inf_prof_res
- [ ] host_progression_lists

### Place parameters

- [ ] place_params
- [ ] place_transmission
- [ ] carehome_params

### Household parameters

- [ ] household_transmission
- [ ] household_size_distribution
- [ ] max_household_size
- [ ] household_age_params

### Age parameters

- [ ] use_ages
- [ ] age_proportions
- [ ] age_contact

**Comment by mghosh00** [comment]
## Input

We also need an input.csv file (see gib_input.csv), hopefully this is produced by EpiGeoPop

**Comment by abbie-evans** [comment]
Household_size_distribution: [0.08518602, 0.20812382, 0.19097004, 0.24683137, 0.16569818, 0.06929404, 0.00847413, 0.00847413, 0.00847413, 0.00847412]

Values calculated from:
https://data.cso.ie/
https://data.cso.ie/table/TAH02

**Comment by KCGallagher** [comment]
@mghosh00 Please closes issues that are no longer active (with some explanation)

**Comment by mghosh00** [comment]
We are no longer simulating the population of Ireland - this is due to simulations taking too long to run. Therefore, we are now looking at smaller populations.
